# Generated by Django 2.0.5 on 2018-08-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('githubapi', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='gh_username',
            new_name='github_username',
        ),
    ]
