# Generated by Django 2.0.5 on 2018-08-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubapi', '0003_auto_20180809_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='github_username',
            field=models.CharField(max_length=100, verbose_name='GitHub Username'),
        ),
    ]
